table dim_customer
	lineageTag: a704fe45-2b60-4a21-8716-a3aaa8c78014

	column customer_unique_id
		dataType: string
		lineageTag: 2deeccc0-76dc-4bc4-8741-8317751ce96b
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		formatString: 0
		lineageTag: 75fc49bc-d66e-44b4-8dc1-8435cfc83218
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		queryGroup: dimensions
		source =
				let
				    Source = olist_customers_dataset,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"customer_zip_code_prefix", "customer_city", "customer_state", "customer_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "customer_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

