table fact_reviews
	lineageTag: d99ec719-cbd2-4f2a-a8ff-320b436153e0

	column review_id
		dataType: string
		lineageTag: 7a98cea0-5157-4b72-b8f8-44f513278ed9
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 7f90a28a-1bda-48f4-91cc-d377fceda439
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column purchase_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b44c7283-7b6a-44f6-a1e4-95aff92a71e2
		summarizeBy: none
		sourceColumn: purchase_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 355b8e0a-5fe3-4c65-900d-c435fb01b0a6
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 14d6fd30-0af9-497c-a3de-783701231f44
		summarizeBy: none
		sourceColumn: review_creation_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column review_answer_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e373c2bf-0352-497e-8b07-14b38205fdc2
		summarizeBy: none
		sourceColumn: review_answer_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column customer_key
		dataType: int64
		formatString: 0
		lineageTag: 2501a7de-e11b-41de-8aaa-b6c1935df743
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column customer_location_key
		dataType: int64
		formatString: 0
		lineageTag: d54f301a-968e-48e6-9d0c-fbcf0e239d80
		summarizeBy: sum
		sourceColumn: customer_location_key

		annotation SummarizationSetBy = Automatic

	partition fact_reviews = m
		mode: import
		queryGroup: Facts
		source =
				let
				    Source = olist_order_reviews_dataset,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"review_comment_title", "review_comment_message"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"order_id"}, fact_orders, {"order_id"}, "fact_orders", JoinKind.LeftOuter),
				    #"Expanded fact_orders" = Table.ExpandTableColumn(#"Merged Queries", "fact_orders", {"customer_key", "customer_location_key", "purchase_date"}, {"fact_orders.customer_key", "fact_orders.customer_location_key", "fact_orders.purchase_date"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded fact_orders",{{"fact_orders.customer_key", "customer_key"}, {"fact_orders.customer_location_key", "customer_location_key"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"review_creation_date", type date}, {"review_answer_timestamp", type date}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"review_answer_timestamp", "review_answer_date"}, {"fact_orders.purchase_date", "purchase_date"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"review_id", "order_id", "purchase_date", "review_score", "review_creation_date", "review_answer_date", "customer_key", "customer_location_key"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

